  - name: Disable default nginx
    ansible.builtin.command: dnf module disable nginx -y

  - name: Enable nginx
    ansible.builtin.command: dnf module enable nginx:1.24 -y

  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start and enable
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true

  - name: Remove html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  
  - name: download frontend code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend code
    ansible.builtin.unarchive:
      src:  /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: true

  - name: remove nginx conf
    ansible.builtin.file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy roboshop nginx conf
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
      - Restart nginx
