  - name: disable default modejs module
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable modejs:20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install modejs:20 module
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Install dependencies
    community.general.npm:
      path: /app 