  - name: copy the catalogue service to system directory
    ansible.builtin.templates:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service
  
  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted  # Even when the app is not running you can restart
      enabled: true